name: shelf_proxy
version: 0.1.0+7
author: Dart Team <misc@dartlang.org>
description: A shelf handler for proxying HTTP requests to another server.
homepage: https://github.com/dart-lang/shelf_proxy

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: '>=0.9.0 <0.13.0'
  path: '>=1.0.0 <2.0.0'
  pedantic: ^1.0.0
  shelf: '>=0.5.2 <0.8.0'

dev_dependencies:
  test: ^1.3.0
